apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: 10.91.4.81
      http:
        paths:
          - path: /
            backend:
              serviceName: master
              servicePort: 8080
    - host: 10.91.4.81
      http:
        paths:
          - path: /*
            backend:
              serviceName: master
              servicePort: 8080