apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  type: ClusterIP
  ports:
    - port: 39000
      targetPort: 39000
      protocol: TCP
      name: user
  selector:
    app: user
